package com.johngori.software.atm.utils;

public enum CurrentScreen {
	
	WELCOME, PINREQUEST, TRANSACTIONS, ERROR, BALANCEINQUIRY, WITHDRAWAL, INSUFFICIENT, WITHDRAWALSUCCESSFUL, DEPOSIT, DEPOSITSUCCESSFUL;
	
}
